### ISSUE TITLE
Extraneous openings on solder paste stencil between R3 and R7

### ISSUE THREAD

**Issue by sampsonlau** [BenjaminPoilve/minichord#7]
In the space between R3 and R7, there appears to be an extra pair of openings on the solder paste stencil that does not align with any solder pads. In the attached image, they are the solder pads highlighted in yellow.
![Screenshot of area of interest.](https://github.com/user-attachments/assets/19f7a7b3-7db1-4eaf-b737-67012caff6e2)

**Comment by BenjaminPoilve** [comment]
Well that's a careful review you did to catch that :)
Yes indeed it should not be on paste. This does not cause any issues, because that footprint is simply used to bridge ground and power ground on a single point. 
I'll fix it shortly!

**Comment by BenjaminPoilve** [comment]
Will be removed in the next commit
