### ISSUE TITLE
Numbers file BOM lists the screws differently from everywhere else

### ISSUE THREAD

**Issue by sampsonlau** [BenjaminPoilve/minichord#8]
full_BOM.numbers lists 9 M2.3x8 screws, but full_BOM.csv and full_BOM.pdf list them as 6 M2.3x8 screws and 3 M2.3x4 screws. Additionally, the assembly instructions on the website mentions 6 long and 3 short screws, which is consistent with the CSV and PDF files, but not the Numbers file.

**Comment by BenjaminPoilve** [comment]
Thanks for the catch. Will be updated in the next commit !
